CREATE TABLE AUTHORS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255)
);

CREATE TABLE BOOKS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255),
    AUTHOR_ID INTEGER REFERENCES AUTHORS (ID)
);